#!/bin/sh

FILE="app.yaml"
/bin/cat <<EOM >$FILE
runtime: nodejs16
env: $APP_ENV
service: $APP_SERVICE
env_variables:
  HOST: $APP_HOST
  NODE_ENV: $NODE_ENV
  DATABASE_NAME: $DATABASE_NAME
  DATABASE_USER: $DATABASE_USER
  DATABASE_PASSWORD: $DATABASE_PASSWORD
  INSTANCE_CONNECTION_NAME: $INSTANCE_CONNECTION_NAME
  APP_KEYS: $APP_KEYS
  API_TOKEN_SALT: $API_TOKEN_SALT
  ADMIN_JWT_SECRET: $ADMIN_JWT_SECRET
  JWT_SECRET: $JWT_SECRET
automatic_scaling:
  min_instances: $MIN_INSTANCES
  max_instances: $MAX_INSTANCES
  target_cpu_utilization: $TARGET_CPU_UTILIZATION
beta_settings:
  cloud_sql_instances: $INSTANCE_CONNECTION_NAME
EOM
